### ISSUE TITLE
Panic at 'invalid coeff' using a private key generated by openssl

### ISSUE THREAD

**Issue by CBenoit** [RustCrypto/RSA#30]
Hi,

I tried playing around with RSA and everything is nice as long as I generate my private keys with the API provided by the crate itself (great!).
I also tried to sign a message using [a private key generated by openssl](https://lapo.it/asn1js/#MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDALwbJC9MJk4r6KIFHl8ZAKbNEJNZf1NDdpEbmAYWTTAHoQWgswDIQSp4beBLzGECbatJZjH2Qq5-81q3eJaVtJFWqRxulUBiWPa9OumoOkmX7q77PEVihQQF6-UkmQCGXwS4Jxw4DfR9Wlx9G9c9O29F3fIVP0T0TBmWO2BIjTbDuBnCDtUjFoZ5qOHkS7PplVBn6o1EqBetELuA9GpXIjoO3Qlz5K7koEY2fRBw8PM5qFaFrWJ5p4yQWKxn2Z2mwmhni3Dl6JwtpSiYrMAsddBW37-txlKsJ3r_u5SjXUH8JgEzhR9KnBdovzwn0AToDn76ej2GYnNoXYsun5DDHjJjeP1MO63FICOytrHEk4ZndfID2cb75hu3dzFnl8_tE6PEJ9E4GZW_l1ifQ704Eiph4IfpCto2lkxp2Us0iHIy_xj4_evmX89orhUloSLmk-iycQ9rCnRbTJkPOaOTbPUu2FpHHRplWsCOUfRFv_qCgtRD2q7XGwO1BVWk3gDz1lSa1NY5GecmvT7n3l4cfGyx3aCnOp_hs-M0hN0AS44IK2m_KLiWzbfPC7OvJRiNxQ4Sexc1D4OtmksrF22wP-o1X-PWF97IGg-WULdxX7ptwY4VxUZuNipv4rDVvT6Mvr1FIpCqCZL6piqvxzjycNHHKrdBeFHyq3NTAEVItWQIDAQABAoICAQCpBrNJD4VE3udUrVtGxE4xEHwCawPAtUQeK-XPVXdN3YOv6hbdhQyDF52HO0wvUh1Ak-r9p3qoSsnrJEU3JJUiMNrHMFM4SgHV4drVu06cElZvytW--NqiuLG8npOfeLgS6Gy9XL0OhHWTisaPepIiIWNRW8tEMBsvKGkaAR-yvRnnvvImZMLkTwktEw4pfxObGyTeM9WmyB3rke7WzxL9mZpvC4cJ_1KR0x5j_Vt3_2LsGqol54MsTgHnHXFwLfPexyoNRPOoY769k-GOCms8NGUFqZXCB6eGvsrAKfyJotqYWKdFXA4BqDwF4Go4mPuVRGI6wpBr0UhfWR0VRLVAxDGC0_JwuORu8ImOuKpPvNYqyYnuXxguzpaab3_5AlHA0IRV0xNcp8I_VwmO51qKyQRBOF9SV22C7yBQM1htD8WKVvZ4p-JfiHVOIzFmpRkdVnJv2dKFtChcne-P8wZUXRAzxPGFczyvYu_2ANhTm32dCVQwuGzSNWNqLjyMcAFsU3IfewRw6Yk4jAmsJfDV3MbsCi3DJoRVQc6YvThN9-bAIV-fKsuNsWCfI56jIggFiNxjtAVGb_2e6lcxMfmFnaqsd8IkinQori00F1CqacdqkWXmXot7WzioFLlsQjOOK2hsu8AWb1ps-UMZ_GZjqaWswrj6fK3AX0K3vBzUAQKCAQEA9kQWEAzsbzOcdPa-s5wFfw4XDd7bB1q9foZ31b1-TNjGNxbSBCFlDF1q98vwpV6nM8bWDh_wtbNoETSQDgpEnYOQ26LWEw6YY1-q1Q2GGEFceYUf-Myk8_vTc8TN6Zw0bKZBWy10Qo8h7xk4JpzuI7NcxvjJYTkS9aErFxi3vVH0aiZC0tmfaCqr8a2rJxyVwqreRpOjwAWrotMsf2wGsF4ofx5ScoFy5GB5fJkkdOrW1LyTvZAUCX3cstPr19-TNC5zZOk7WzZatnCkN5H5WzalWtZuu0oVL205KPOa3R8V2yv5e6fm0v5fTmqSuvjmaMJLXCN4QJkmIzojO99ckQKCAQEAx8exdMjVA2CiI-Thx7loHtVcevoeE2sZ7btRVAvmBqo-lkHwxb7FHRnWvuj6eJSlD2f0T50EewIhhiW3R9BmktCk7hXjbSCnC1u9Oxc1IAUm_7azRqyfCMx43XhLxpD-xkBCpWkKDLxGczsRwTuaP3lKS3bSdBrNlGmdblubvVBIq4YZ2vXVlnYtza0cS-dgCK7BGTqUsrCUd_ZbIvwcwZkZtpkhj1KQfto9X_0OMurBzAqbkeq1cyRHXHkOfN_qbUIIRqr9Ii7Eswf9Vk8xp2O1Nt8nzcYS9PFD12M5eyaeFEkEYfpNMNGuTzp_31oqVjbpoCxS6vuWAZyADxhISQKCAQEAis7d0LY4HoXszlC2NO7gejkq7XqL4p1W6hZJPYTNx-r37t1CC2n3Vvzg6kNdpRixDhIpXVTLjN9O7UO_XuqSumYKJIKoP52eb4Tg-a3hw5Iz2Zsb5lUTNSLgkQSBPAf71LHxbL82JL4g1nBUog8ae60BwnVArThKY4EwlJguGNw09BAU4lwf6csDl_nX2vfVwiAloYpeZkHL-L8m-bueGZM5KE2jEz-7ztZCI-T-E5i69rZEYDjx0lfLKlEhQlCW3HbCPELqXgNJJkRfi6MP9kXa9lSfnZmoT081RMvqonB_FUa4HOcKyCrw9XZEtnbNCIdbitfDVEX-pSSD7596wQKCAQAY-zSKeO6B_Jxpxp4g_mMxr9ZfnlUScosMeibiTpaV8MXgviAgagl16Rw8RR_E4jl9oq8fIXBE_XA5uQ-hEEMzSpnFF8GXjMS2m-Met3kyJtLImQzz4nQEgqT-dKNtEgZ5veFXk7no-8YHdLR0qEJSe5U5uIL6d7uLOmWwPg5MbvSXVi53fdQWe3KgzGvEZgtRKqEEyZl8eq4mDg05Y7Mo1j8r4RwcMuPUqO-RyC_1V_uhyxXG-kV0P24Y9x5DqTBEN0SXqZv7oUOBa5dXKpH373TihqcQiRsnu9-S2FqAtsR_nt3IbqcmWqHkUFlbEYhHvZgbKk-4CHuqeepdeNjZAoIBAAlFgvoUVjk-NtZMEZZYFY8uhWL-o0FHIAzR3gImGZ3-R40vYitpIu7_BuXS_9H_mH_jYRP-KvMOJvIKOdYQAq1aT9afBiQ44k9PfkbDsyE7B8JfnHhCqHuemVuogxwS5azcOfzLXGISqYzVPSidrnZuSf3PYorJXI4HJK2RtiAfAA4FxzBAcmeQ4GjJeACmdRsfP6uin7U75jk-azUzC4u-lTeSlkHA1ivw6l4jomRzOza-HV-Jnt13kYAAScjUfBasY9zdfh62C3v87OyzmitPvhfVJd7S3pYa4bLy8Xot6AmZBfQP36A96J95bmAPtXEXMVqUmN4dieP9tvsqOPk). It worked for most of the generated keys but not this one.

The public exponent is `65537` and the other components in base64 are : 

- n: `wC8GyQvTCZOK+iiBR5fGQCmzRCTWX9TQ3aRG5gGFk0wB6EFoLMAyEEqeG3gS8xhAm2rSWYx9kKufvNat3iWlbSRVqkcbpVAYlj2vTrpqDpJl+6u+zxFYoUEBevlJJkAhl8EuCccOA30fVpcfRvXPTtvRd3yFT9E9EwZljtgSI02w7gZwg7VIxaGeajh5Euz6ZVQZ+qNRKgXrRC7gPRqVyI6Dt0Jc+Su5KBGNn0QcPDzOahWha1ieaeMkFisZ9mdpsJoZ4tw5eicLaUomKzALHXQVt+/rcZSrCd6/7uUo11B/CYBM4UfSpwXaL88J9AE6A5++no9hmJzaF2LLp+Qwx4yY3j9TDutxSAjsraxxJOGZ3XyA9nG++Ybt3cxZ5fP7ROjxCfROBmVv5dYn0O9OBIqYeCH6QraNpZMadlLNIhyMv8Y+P3r5l/PaK4VJaEi5pPosnEPawp0W0yZDzmjk2z1LthaRx0aZVrAjlH0Rb/6goLUQ9qu1xsDtQVVpN4A89ZUmtTWORnnJr0+595eHHxssd2gpzqf4bPjNITdAEuOCCtpvyi4ls23zwuzryUYjcUOEnsXNQ+DrZpLKxdtsD/qNV/j1hfeyBoPllC3cV+6bcGOFcVGbjYqb+Kw1b0+jL69RSKQqgmS+qYqr8c48nDRxyq3QXhR8qtzUwBFSLVk=`
- d: `qQazSQ+FRN7nVK1bRsROMRB8AmsDwLVEHivlz1V3Td2Dr+oW3YUMgxedhztML1IdQJPq/ad6qErJ6yRFNySVIjDaxzBTOEoB1eHa1btOnBJWb8rVvvjaorixvJ6Tn3i4EuhsvVy9DoR1k4rGj3qSIiFjUVvLRDAbLyhpGgEfsr0Z577yJmTC5E8JLRMOKX8Tmxsk3jPVpsgd65Hu1s8S/ZmabwuHCf9SkdMeY/1bd/9i7BqqJeeDLE4B5x1xcC3z3scqDUTzqGO+vZPhjgprPDRlBamVwgenhr7KwCn8iaLamFinRVwOAag8BeBqOJj7lURiOsKQa9FIX1kdFUS1QMQxgtPycLjkbvCJjriqT7zWKsmJ7l8YLs6Wmm9/+QJRwNCEVdMTXKfCP1cJjudaiskEQThfUldtgu8gUDNYbQ/Filb2eKfiX4h1TiMxZqUZHVZyb9nShbQoXJ3vj/MGVF0QM8TxhXM8r2Lv9gDYU5t9nQlUMLhs0jVjai48jHABbFNyH3sEcOmJOIwJrCXw1dzG7AotwyaEVUHOmL04TffmwCFfnyrLjbFgnyOeoyIIBYjcY7QFRm/9nupXMTH5hZ2qrHfCJIp0KK4tNBdQqmnHapFl5l6Le1s4qBS5bEIzjitobLvAFm9abPlDGfxmY6mlrMK4+nytwF9Ct7wc1AE=`
- prime 1: `9kQWEAzsbzOcdPa+s5wFfw4XDd7bB1q9foZ31b1+TNjGNxbSBCFlDF1q98vwpV6nM8bWDh/wtbNoETSQDgpEnYOQ26LWEw6YY1+q1Q2GGEFceYUf+Myk8/vTc8TN6Zw0bKZBWy10Qo8h7xk4JpzuI7NcxvjJYTkS9aErFxi3vVH0aiZC0tmfaCqr8a2rJxyVwqreRpOjwAWrotMsf2wGsF4ofx5ScoFy5GB5fJkkdOrW1LyTvZAUCX3cstPr19+TNC5zZOk7WzZatnCkN5H5WzalWtZuu0oVL205KPOa3R8V2yv5e6fm0v5fTmqSuvjmaMJLXCN4QJkmIzojO99ckQ==`
- prime 2: `x8exdMjVA2CiI+Thx7loHtVcevoeE2sZ7btRVAvmBqo+lkHwxb7FHRnWvuj6eJSlD2f0T50EewIhhiW3R9BmktCk7hXjbSCnC1u9Oxc1IAUm/7azRqyfCMx43XhLxpD+xkBCpWkKDLxGczsRwTuaP3lKS3bSdBrNlGmdblubvVBIq4YZ2vXVlnYtza0cS+dgCK7BGTqUsrCUd/ZbIvwcwZkZtpkhj1KQfto9X/0OMurBzAqbkeq1cyRHXHkOfN/qbUIIRqr9Ii7Eswf9Vk8xp2O1Nt8nzcYS9PFD12M5eyaeFEkEYfpNMNGuTzp/31oqVjbpoCxS6vuWAZyADxhISQ==`
- prime 3: `is7d0LY4HoXszlC2NO7gejkq7XqL4p1W6hZJPYTNx+r37t1CC2n3Vvzg6kNdpRixDhIpXVTLjN9O7UO/XuqSumYKJIKoP52eb4Tg+a3hw5Iz2Zsb5lUTNSLgkQSBPAf71LHxbL82JL4g1nBUog8ae60BwnVArThKY4EwlJguGNw09BAU4lwf6csDl/nX2vfVwiAloYpeZkHL+L8m+bueGZM5KE2jEz+7ztZCI+T+E5i69rZEYDjx0lfLKlEhQlCW3HbCPELqXgNJJkRfi6MP9kXa9lSfnZmoT081RMvqonB/FUa4HOcKyCrw9XZEtnbNCIdbitfDVEX+pSSD7596wQ==`
- prime 4: `GPs0injugfycacaeIP5jMa/WX55VEnKLDHom4k6WlfDF4L4gIGoJdekcPEUfxOI5faKvHyFwRP1wObkPoRBDM0qZxRfBl4zEtpvjHrd5MibSyJkM8+J0BIKk/nSjbRIGeb3hV5O56PvGB3S0dKhCUnuVObiC+ne7izplsD4OTG70l1Yud33UFntyoMxrxGYLUSqhBMmZfHquJg4NOWOzKNY/K+EcHDLj1Kjvkcgv9Vf7ocsVxvpFdD9uGPceQ6kwRDdEl6mb+6FDgWuXVyqR9+904oanEIkbJ7vfkthagLbEf57dyG6nJlqh5FBZWxGIR72YGypPuAh7qnnqXXjY2Q==`
- prime 5: `CUWC+hRWOT421kwRllgVjy6FYv6jQUcgDNHeAiYZnf5HjS9iK2ki7v8G5dL/0f+Yf+NhE/4q8w4m8go51hACrVpP1p8GJDjiT09+RsOzITsHwl+ceEKoe56ZW6iDHBLlrNw5/MtcYhKpjNU9KJ2udm5J/c9iislcjgckrZG2IB8ADgXHMEByZ5DgaMl4AKZ1Gx8/q6KftTvmOT5rNTMLi76VN5KWQcDWK/DqXiOiZHM7Nr4dX4me3XeRgABJyNR8Fqxj3N1+HrYLe/zs7LOaK0++F9Ul3tLelhrhsvLxei3oCZkF9A/foD3on3luYA+1cRcxWpSY3h2J4/22+yo4+Q==`

Here is a minimal code:

```rust
let n = base64::decode("wC8GyQvTCZOK+iiBR5fGQCmzRCTWX9TQ3aRG5gGFk0wB6EFoLMAyEEqeG3gS8xhAm2rSWYx9kKufvNat3iWlbSRVqkcbpVAYlj2vTrpqDpJl+6u+zxFYoUEBevlJJkAhl8EuCccOA30fVpcfRvXPTtvRd3yFT9E9EwZljtgSI02w7gZwg7VIxaGeajh5Euz6ZVQZ+qNRKgXrRC7gPRqVyI6Dt0Jc+Su5KBGNn0QcPDzOahWha1ieaeMkFisZ9mdpsJoZ4tw5eicLaUomKzALHXQVt+/rcZSrCd6/7uUo11B/CYBM4UfSpwXaL88J9AE6A5++no9hmJzaF2LLp+Qwx4yY3j9TDutxSAjsraxxJOGZ3XyA9nG++Ybt3cxZ5fP7ROjxCfROBmVv5dYn0O9OBIqYeCH6QraNpZMadlLNIhyMv8Y+P3r5l/PaK4VJaEi5pPosnEPawp0W0yZDzmjk2z1LthaRx0aZVrAjlH0Rb/6goLUQ9qu1xsDtQVVpN4A89ZUmtTWORnnJr0+595eHHxssd2gpzqf4bPjNITdAEuOCCtpvyi4ls23zwuzryUYjcUOEnsXNQ+DrZpLKxdtsD/qNV/j1hfeyBoPllC3cV+6bcGOFcVGbjYqb+Kw1b0+jL69RSKQqgmS+qYqr8c48nDRxyq3QXhR8qtzUwBFSLVk=").unwrap();
let e = base64::decode("AQAB").unwrap();
let d = base64::decode("qQazSQ+FRN7nVK1bRsROMRB8AmsDwLVEHivlz1V3Td2Dr+oW3YUMgxedhztML1IdQJPq/ad6qErJ6yRFNySVIjDaxzBTOEoB1eHa1btOnBJWb8rVvvjaorixvJ6Tn3i4EuhsvVy9DoR1k4rGj3qSIiFjUVvLRDAbLyhpGgEfsr0Z577yJmTC5E8JLRMOKX8Tmxsk3jPVpsgd65Hu1s8S/ZmabwuHCf9SkdMeY/1bd/9i7BqqJeeDLE4B5x1xcC3z3scqDUTzqGO+vZPhjgprPDRlBamVwgenhr7KwCn8iaLamFinRVwOAag8BeBqOJj7lURiOsKQa9FIX1kdFUS1QMQxgtPycLjkbvCJjriqT7zWKsmJ7l8YLs6Wmm9/+QJRwNCEVdMTXKfCP1cJjudaiskEQThfUldtgu8gUDNYbQ/Filb2eKfiX4h1TiMxZqUZHVZyb9nShbQoXJ3vj/MGVF0QM8TxhXM8r2Lv9gDYU5t9nQlUMLhs0jVjai48jHABbFNyH3sEcOmJOIwJrCXw1dzG7AotwyaEVUHOmL04TffmwCFfnyrLjbFgnyOeoyIIBYjcY7QFRm/9nupXMTH5hZ2qrHfCJIp0KK4tNBdQqmnHapFl5l6Le1s4qBS5bEIzjitobLvAFm9abPlDGfxmY6mlrMK4+nytwF9Ct7wc1AE=").unwrap();
let primes = vec![
    base64::decode("9kQWEAzsbzOcdPa+s5wFfw4XDd7bB1q9foZ31b1+TNjGNxbSBCFlDF1q98vwpV6nM8bWDh/wtbNoETSQDgpEnYOQ26LWEw6YY1+q1Q2GGEFceYUf+Myk8/vTc8TN6Zw0bKZBWy10Qo8h7xk4JpzuI7NcxvjJYTkS9aErFxi3vVH0aiZC0tmfaCqr8a2rJxyVwqreRpOjwAWrotMsf2wGsF4ofx5ScoFy5GB5fJkkdOrW1LyTvZAUCX3cstPr19+TNC5zZOk7WzZatnCkN5H5WzalWtZuu0oVL205KPOa3R8V2yv5e6fm0v5fTmqSuvjmaMJLXCN4QJkmIzojO99ckQ==").unwrap(),
    base64::decode("x8exdMjVA2CiI+Thx7loHtVcevoeE2sZ7btRVAvmBqo+lkHwxb7FHRnWvuj6eJSlD2f0T50EewIhhiW3R9BmktCk7hXjbSCnC1u9Oxc1IAUm/7azRqyfCMx43XhLxpD+xkBCpWkKDLxGczsRwTuaP3lKS3bSdBrNlGmdblubvVBIq4YZ2vXVlnYtza0cS+dgCK7BGTqUsrCUd/ZbIvwcwZkZtpkhj1KQfto9X/0OMurBzAqbkeq1cyRHXHkOfN/qbUIIRqr9Ii7Eswf9Vk8xp2O1Nt8nzcYS9PFD12M5eyaeFEkEYfpNMNGuTzp/31oqVjbpoCxS6vuWAZyADxhISQ==").unwrap(),
    base64::decode("is7d0LY4HoXszlC2NO7gejkq7XqL4p1W6hZJPYTNx+r37t1CC2n3Vvzg6kNdpRixDhIpXVTLjN9O7UO/XuqSumYKJIKoP52eb4Tg+a3hw5Iz2Zsb5lUTNSLgkQSBPAf71LHxbL82JL4g1nBUog8ae60BwnVArThKY4EwlJguGNw09BAU4lwf6csDl/nX2vfVwiAloYpeZkHL+L8m+bueGZM5KE2jEz+7ztZCI+T+E5i69rZEYDjx0lfLKlEhQlCW3HbCPELqXgNJJkRfi6MP9kXa9lSfnZmoT081RMvqonB/FUa4HOcKyCrw9XZEtnbNCIdbitfDVEX+pSSD7596wQ==").unwrap(),
    base64::decode("GPs0injugfycacaeIP5jMa/WX55VEnKLDHom4k6WlfDF4L4gIGoJdekcPEUfxOI5faKvHyFwRP1wObkPoRBDM0qZxRfBl4zEtpvjHrd5MibSyJkM8+J0BIKk/nSjbRIGeb3hV5O56PvGB3S0dKhCUnuVObiC+ne7izplsD4OTG70l1Yud33UFntyoMxrxGYLUSqhBMmZfHquJg4NOWOzKNY/K+EcHDLj1Kjvkcgv9Vf7ocsVxvpFdD9uGPceQ6kwRDdEl6mb+6FDgWuXVyqR9+904oanEIkbJ7vfkthagLbEf57dyG6nJlqh5FBZWxGIR72YGypPuAh7qnnqXXjY2Q==").unwrap(),
    base64::decode("CUWC+hRWOT421kwRllgVjy6FYv6jQUcgDNHeAiYZnf5HjS9iK2ki7v8G5dL/0f+Yf+NhE/4q8w4m8go51hACrVpP1p8GJDjiT09+RsOzITsHwl+ceEKoe56ZW6iDHBLlrNw5/MtcYhKpjNU9KJ2udm5J/c9iislcjgckrZG2IB8ADgXHMEByZ5DgaMl4AKZ1Gx8/q6KftTvmOT5rNTMLi76VN5KWQcDWK/DqXiOiZHM7Nr4dX4me3XeRgABJyNR8Fqxj3N1+HrYLe/zs7LOaK0++F9Ul3tLelhrhsvLxei3oCZkF9A/foD3on3luYA+1cRcxWpSY3h2J4/22+yo4+Q==").unwrap(),
];

RSAPrivateKey::from_components(
    BigUint::from_bytes_be(&n),
    BigUint::from_bytes_be(&e),
    BigUint::from_bytes_be(&d),
    primes
        .iter()
        .map(|p| BigUint::from_bytes_be(p))
        .collect(),
);
```

You should get a backtrace similar to:
```
thread '<unnamed>' panicked at 'invalid coeff', src/libcore/option.rs:1185:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::option::expect_failed
             at src/libcore/option.rs:1185
  15: core::option::Option<T>::expect
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libcore/option.rs:345
  16: rsa::key::RSAPrivateKey::precompute::{{closure}}
             at /home/bcortier/.cargo/registry/src/github.com-1ecc6299db9ec823/rsa-0.1.4/src/key.rs:336
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libcore/ops/function.rs:275
  18: core::option::Option<T>::map
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libcore/option.rs:447
  19: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libcore/iter/adapters/mod.rs:710
  20: alloc::vec::Vec<T>::extend_desugared
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/liballoc/vec.rs:2108
  21: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/liballoc/vec.rs:2005
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/liballoc/vec.rs:2000
  23: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/liballoc/vec.rs:1901
  24: core::iter::traits::iterator::Iterator::collect
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libcore/iter/traits/iterator.rs:1493
  25: rsa::key::RSAPrivateKey::precompute
             at /home/bcortier/.cargo/registry/src/github.com-1ecc6299db9ec823/rsa-0.1.4/src/key.rs:326
  26: rsa::key::RSAPrivateKey::from_components
             at /home/bcortier/.cargo/registry/src/github.com-1ecc6299db9ec823/rsa-0.1.4/src/key.rs:298
  27: picky::models::signature::SignatureHashType::sign
             at picky/src/models/signature.rs:58
```

It looks like the mod_inverse operation from num_bigint_dig returns None here: https://github.com/RustCrypto/RSA/blob/master/src/key.rs#L337

**Comment by CBenoit** [comment]
Fixed by https://github.com/RustCrypto/RSA/issues/30 :+1:
